stages:
  - test

armv8_testsuite:
  stage: test
  image:
    name: python
    entrypoint: [""]
  cache:
    - key:
        files:
          - armv8_testsuite/requirements.txt
      paths:
        - armv8_testsuite/.venv/
    - key: cache-arm-gnu-toolchain
      paths:
        - armv8_testsuite/arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-elf/
  artifacts:
    paths:
      - armv8_testsuite/test/actual_results/
  script:
    - cd src
    - make
    - cd ../armv8_testsuite
    - ./install
    - ./get_toolchain.sh
    - ./run -p --toolchain ./arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-elf/bin/
    - grep -q FAILED test/actual_results/results.json && exit 1 || exit 0
