stages:
  - test

armv8_testsuite:
  stage: test
  image:
    name: python
    entrypoint: ["/bin/bash"]
  cache:
    - key:
        files:
          - armv8_testsuite/requirements.txt
      paths:
        - armv8_testsuite/.venv/
    - key: cache-arm-gnu-toolchain
      paths:
        - armv8_testsuite/arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-elf/
  artifacts:
    paths:
      - test/actual_results/
  script:
    - cd src
    - make
    - cd ../armv8_testsuite
    - ./install
    - |
      if [ ! -f arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-elf ]; then
        wget https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-elf.tar.xz
        tar -xvf arm-gnu-toolchain-13.2.rel1-x86_64-aarch64-none-elf.tar.xz
      fi
    - ./run -p --toolchain ./arm-gnu-toolchain-13.2.Rel1-x86_64-aarch64-none-elf/bin/
