#!/bin/sh

# Run the server or commandline
# Tries to run with the venv, else with python3

RUN_SCRIPT="armv8suite.run_cli"
SERVER="armv8server.app"


run_server=false
dbg_server=false

while getopts ":sd" flag
do
    case "${flag}" in
        s) run_server=true;
            echo "Running Flask Server." ;
            break;;
        d) dbg_server=true;
            run_server=true;
            echo "Running Flask Server in Debug Mode." ;
            break;;
        \?) break ;;
        *) break ;;
    esac
done


if [ -e .venv/bin/python3 ]
then
    . ./.venv/bin/activate
fi

if [ $dbg_server = true ]; then dbg_arg="--debug"; else dbg_arg=""; fi

if [ "$run_server" = true ]
then
    python3 -m flask ${dbg_arg} --app ${SERVER} run
else
    python3 -m ${RUN_SCRIPT} $@
fi
